import React, {createContext, useState, useContext, useEffect, useCallback, ReactNode} from 'react';
import api from '../../services';
import session from '../../services/session';
import { AuthContextValue, User, UserRole } from '../../types';

const AuthContext = createContext<AuthContextValue | undefined>(undefined);

export const useAuth = (): AuthContextValue => {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};

interface AuthProviderProps {
  children: ReactNode;
}

export const AuthProvider: React.FC<AuthProviderProps> = ({children}) => {
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [loading, setLoading] = useState<boolean>(true); // To check auth status on initial load

  // Function to process a received token (from OAuth or direct login)
  const processAuthToken = useCallback(async (token: string, tokenType: string = 'Bearer'): Promise<User> => {
    try {
      // The bearer lives only in module memory; the axios interceptor in
      // config.ts attaches it to same-origin API calls.
      session.setBearerSession(token, tokenType);

      const userData = await api.auth.me(); // Fetch user details using the new token
      if (userData) {
        setCurrentUser(userData);
        // console.log('User details fetched and context updated:', userData);
        return userData;
      } else {
        throw new Error('User data not found after token processing.');
      }
    } catch (error) {
      console.error('Failed to process auth token or fetch user:', error);
      session.clearBearerSession();
      setCurrentUser(null);
      throw error;
    }
  }, []);

  // Function to handle login (Email/Password)
  const login = async (email: string, password: string): Promise<User> => {
    try {
      const authData = await api.auth.login(email, password);

      if (authData && authData.accessToken && authData.user) {
        // processAuthToken will be called with the token, and it will fetch the user
        await processAuthToken(authData.accessToken, authData.tokenType || 'Bearer');
        // The user object is returned for immediate use if needed, though context will update
        return authData.user;
      } else {
        const errorMessage = 'Login failed: Invalid data structure from API.';
        console.error(errorMessage, authData);
        throw new Error(errorMessage);
      }
    } catch (error) {
      console.error('Login failed (AuthContext catch block):', (error as Error).message || error);
      throw error;
    }
  };

  const signup = async (
    email: string,
    password: string,
    firstName: string,
    lastName: string,
    role: UserRole = 'PATIENT',
    clinicName: string | null = null,
    existingClinicId: number | null = null
  ): Promise<any> => {
    try {
      console.log(`Attempting signup for ${email}`);

      const signupData: any = {
        email,
        password,
        firstName,
        lastName,
        role
      };

      if (clinicName) signupData.clinicName = clinicName;
      if (existingClinicId) signupData.existingClinicId = existingClinicId;

      const responseMessage = await api.auth.signup(signupData);

      console.log('Signup successful:', responseMessage);
      return {...signupData, emailVerificationPending: true, message: responseMessage};
    } catch (error) {
      console.error('Signup failed:', error);
      throw error;
    }
  };

  const logout = useCallback(async (): Promise<void> => {
    try {
      await api.auth.logout();
    } catch (error) {
      console.error('Backend logout error (will proceed with client-side logout):', error);
    } finally {
      // The auth service already cleared the in-memory bearer/XSRF state and
      // broadcast the session end to other tabs.
      setCurrentUser(null);
    }
  }, []);

  // ---- GOOGLE OAUTH (ID-TOKEN POPUP FLOW) ----
  // This helper receives the `credential` (ID token) generated by the
  // Google Identity Services popup. It forwards the token to the backend,
  // then stores & processes the internal JWT returned by our API.

  const googleIdLogin = useCallback(async (idToken: string): Promise<User> => {
    try {
      if (!idToken) throw new Error('Missing Google ID token');

      console.log('Received Google ID token, sending to backend for verification…');

      const backendTokenData = await api.auth.loginWithGoogleIdToken(idToken);

      if (backendTokenData && backendTokenData.accessToken) {
        await processAuthToken(backendTokenData.accessToken, backendTokenData.tokenType || 'Bearer');
        console.log('Google login successful – internal session established.');
        return backendTokenData.user || null;
      }
      throw new Error('Invalid response from backend after Google ID token exchange.');
    } catch (error) {
      console.error('Google ID-token login failed:', error);
      throw error;
    }
  }, [processAuthToken]);

  // Check authentication status on initial load
  useEffect(() => {
    const checkAuth = async () => {
      setLoading(true);
      // Prewarm the in-memory XSRF token so cookie-backed refresh and logout
      // keep working after a page reload wiped module state. Single-flight
      // in the auth service (StrictMode-safe) and never rejects.
      void session.ensureXsrfBootstrapped();

      // A page reload wipes the in-memory bearer: restore the session from
      // the HttpOnly refresh cookie when one exists. A failed restore just
      // means the visitor is anonymous — no logout, no redirect.
      let sessionAvailable = session.hasBearerSession();
      if (!sessionAvailable) {
        try {
          await api.auth.refresh();
          sessionAvailable = session.hasBearerSession();
        } catch (_) {
          sessionAvailable = false;
        }
      }

      if (sessionAvailable) {
        try {
          const userData = await api.auth.me();
          if (userData) {
            setCurrentUser(userData);
          } else {
            throw new Error("User data not found during initial auth check");
          }
        } catch (error) {
          console.error('Session verification failed during initial load:', error);
          await logout();
        }
      }
      setLoading(false);
    };

    checkAuth();
  }, [logout, processAuthToken]); // Added processAuthToken to ensure it's stable if defined inside AuthProvider

  const value: AuthContextValue = {
    currentUser,
    isAuthenticated: !!currentUser,
    loading,
    login,
    signup,
    logout,
    googleIdLogin,
    processAuthToken
  };

  return (
      <AuthContext.Provider value={value}>
        {/* Render children only after initial auth check, or always show children and let them adapt */}
        {children}
      </AuthContext.Provider>
  );
};